/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ItineraryViewRouteImport } from './routes/itinerary-view'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsNewRouteImport } from './routes/trips.new'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryViewRoute = ItineraryViewRouteImport.update({
  id: '/itinerary-view',
  path: '/itinerary-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/itinerary': typeof ItineraryRoute
  '/itinerary-view': typeof ItineraryViewRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/itinerary': typeof ItineraryRoute
  '/itinerary-view': typeof ItineraryViewRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/trips/new': typeof TripsNewRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/itinerary': typeof ItineraryRoute
  '/itinerary-view': typeof ItineraryViewRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/auth'
    | '/budget'
    | '/cities'
    | '/dashboard'
    | '/itinerary'
    | '/itinerary-view'
    | '/notes'
    | '/packing'
    | '/profile'
    | '/share'
    | '/trips/new'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/auth'
    | '/budget'
    | '/cities'
    | '/dashboard'
    | '/itinerary'
    | '/itinerary-view'
    | '/notes'
    | '/packing'
    | '/profile'
    | '/share'
    | '/trips/new'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/auth'
    | '/budget'
    | '/cities'
    | '/dashboard'
    | '/itinerary'
    | '/itinerary-view'
    | '/notes'
    | '/packing'
    | '/profile'
    | '/share'
    | '/trips/new'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AuthRoute: typeof AuthRoute
  BudgetRoute: typeof BudgetRoute
  CitiesRoute: typeof CitiesRoute
  DashboardRoute: typeof DashboardRoute
  ItineraryRoute: typeof ItineraryRoute
  ItineraryViewRoute: typeof ItineraryViewRoute
  NotesRoute: typeof NotesRoute
  PackingRoute: typeof PackingRoute
  ProfileRoute: typeof ProfileRoute
  ShareRoute: typeof ShareRoute
  TripsNewRoute: typeof TripsNewRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary-view': {
      id: '/itinerary-view'
      path: '/itinerary-view'
      fullPath: '/itinerary-view'
      preLoaderRoute: typeof ItineraryViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AuthRoute: AuthRoute,
  BudgetRoute: BudgetRoute,
  CitiesRoute: CitiesRoute,
  DashboardRoute: DashboardRoute,
  ItineraryRoute: ItineraryRoute,
  ItineraryViewRoute: ItineraryViewRoute,
  NotesRoute: NotesRoute,
  PackingRoute: PackingRoute,
  ProfileRoute: ProfileRoute,
  ShareRoute: ShareRoute,
  TripsNewRoute: TripsNewRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
